---
# tasks file for ansible-role-desktop-extra
- name: Install Desktop extra packages
  apt:
    name:
      - shutter # feature-rich screenshot program
    update_cache: yes

- name: Install AnyDesk
  apt:
    deb: https://download.anydesk.com/linux/anydesk_2.9.7-1_amd64.deb?_ga=2.141574386.1769291907.1532323313-1948359072.1532323313
